sudo: false

language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "node"

services:
  - redis

before_script:
  - redis-server --port 6378 --requirepass secret &
  - redis-server --port 6377 --unixsocket /tmp/redis.sock &
  - sleep 2
